spring:
  kafka:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.value.default.type: com.hps.Transfer.DTOS.TransferDTO

  application:
    name: TransferMicroservice
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/Transfer
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform : org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083

